"use client";

import type { EducationContract, TeacherTask } from "@/lib/edupi-education-contract";
import { filterTimetableSlots, type CalendarItemSelection } from "@/lib/edupi-calendar-model";
import type { TeacherContextSnapshot } from "@/lib/edupi-onboarding-types";
import { routePart, type TeachingSectionId } from "@/lib/edupi-domain-navigation";
import { isUserFacingMemory, taskDisplayTitle, taskKey, taskStatusLabel } from "@/lib/edupi-workbench";
import { EduPiTimetableGrid } from "./EduPiTimetableGrid";

function shortDate(value: string | null): string {
  if (!value) return "—";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit" }).format(date);
}

export function EduPiTeachingWorkspace({ data, context, query, selectedObjectId, onObject, onTask, onNavigate, onUpload, onStartAgent, onCalendarSelection }: { data: EducationContract; context: TeacherContextSnapshot | null; query: string; selectedObjectId: string | null; onObject: (id: string) => void; onTask: (task: TeacherTask) => void; onNavigate: (view: "calendar" | "tasks" | "memory", objectId?: string) => void; onUpload: () => void; onStartAgent: (prompt: string) => void; onCalendarSelection: (selection: CalendarItemSelection) => void }) {
  const section = routePart(selectedObjectId, "teaching", "home") as TeachingSectionId;
  const slots = filterTimetableSlots(data.timetable, query);
  const knowledge = data.continuity.subjectKnowledge.filter((item) => !query || `${item.subject} ${item.topic} ${item.commonErrors.map((error) => error.description).join(" ")}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const tasks = data.tasks.filter((task) => (task.trigger === "teaching_adjustment_candidate" || task.materialId || task.topic) && (!query || `${task.title} ${task.topic || ""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())));
  const memories = data.continuity.memories.filter((memory) => memory.state === "active" && memory.category === "teaching" && isUserFacingMemory(memory) && (!query || `${memory.content} ${memory.tags.join(" ")}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())));
  const weekday = new Date().getDay() || 7;
  const orderedSlots = data.timetable.slice().sort((left, right) => Number(left.day_of_week) - Number(right.day_of_week) || Number(left.period) - Number(right.period));
  const nextSlot = orderedSlots.find((slot) => Number(slot.day_of_week) >= weekday) || orderedSlots[0];
  const nextSubject = String(nextSlot?.subject || context?.subject || "下一节课");
  const subjectLabel = [context?.subject, context?.grade].filter(Boolean).join(" · ") || "教学工作区";
  const selectCourse = (selection: CalendarItemSelection) => { onCalendarSelection(selection); onNavigate("calendar"); };

  const header = <header className="edupi-module-heading edupi-teaching-heading"><div>{section !== "home" ? <button type="button" className="edupi-back-link" onClick={() => onObject("teaching:home")}>← 教学首页</button> : <span>教学工作区</span>}<h1>{section === "home" ? "教学" : section === "schedule" ? "课程表" : section === "knowledge" ? "教学重点" : section === "tasks" ? "备课任务" : "教学记忆"}</h1><p>{subjectLabel}</p></div><div className="edupi-teaching-heading__actions"><button type="button" onClick={onUpload}>导入教学重点</button><button type="button" className="is-primary" onClick={() => onStartAgent(`请为${nextSubject}准备下一节课的重点、材料和课堂检查点，结合现有学情与教育记忆，先给我可审核候选。`)}>准备下一节课</button></div></header>;

  if (section === "schedule") return <main className="edupi-module-workspace edupi-teaching-workspace">{header}<EduPiTimetableGrid slots={slots} onSelect={selectCourse} /></main>;
  if (section === "knowledge") return <main className="edupi-module-workspace edupi-teaching-workspace">{header}<section className="edupi-database"><div className="edupi-database__head edupi-teaching-knowledge-grid"><span>主题</span><span>共性问题</span><span>需关注学生</span><span>掌握度</span></div>{knowledge.map((item) => <details className="edupi-database-row" key={item.id}><summary className="edupi-teaching-knowledge-grid"><strong>{item.topic}</strong><span>{item.commonErrors[0]?.description || "暂无"}</span><span>{item.strugglingStudents.join("、") || "—"}</span><span>{item.mastery === null ? "—" : `${Math.round(item.mastery * 100)}%`}</span></summary><div className="edupi-database-row__detail"><div><span>学科</span><strong>{item.subject}</strong></div><div><span>前置知识</span><strong>{item.prerequisites.join("、") || "—"}</strong></div><div><span>最近更新</span><strong>{shortDate(item.updatedAt)}</strong></div></div></details>)}</section></main>;
  if (section === "tasks") return <main className="edupi-module-workspace edupi-teaching-workspace">{header}<section className="edupi-database"><div className="edupi-database__head edupi-teaching-task-grid"><span>任务</span><span>主题</span><span>截止</span><span>状态</span></div>{tasks.map((task) => <button type="button" className="edupi-database-button-row edupi-teaching-task-grid" key={taskKey(task)} onClick={() => onTask(task)}><strong>{taskDisplayTitle(task)}</strong><span>{task.topic || task.sourceEventName || "教学准备"}</span><span>{task.dueDate || "待确认"}</span><span>{taskStatusLabel(task)}</span></button>)}</section></main>;
  if (section === "memory") return <main className="edupi-module-workspace edupi-teaching-workspace">{header}<section className="edupi-database"><div className="edupi-database__head edupi-teaching-memory-grid"><span>记忆</span><span>标签</span><span>累计</span><span>更新</span></div>{memories.map((memory) => <details className="edupi-database-row" key={memory.id}><summary className="edupi-teaching-memory-grid"><strong>{memory.content}</strong><span>{memory.tags.slice(0, 3).join(" · ") || "—"}</span><span>{memory.count} 次</span><span>{shortDate(memory.updatedAt || memory.createdAt)}</span></summary><div className="edupi-database-row__detail"><button type="button" onClick={() => onNavigate("memory", "memory:teaching")}>打开教育记忆</button></div></details>)}</section></main>;

  return <main className="edupi-module-workspace edupi-teaching-workspace">{header}<section className="edupi-teaching-next-line"><div><span>下一节课</span><strong>{nextSubject}</strong><p>{nextSlot ? `周${String(nextSlot.day_of_week)} · 第 ${String(nextSlot.period)} 节${nextSlot.class_name ? ` · ${String(nextSlot.class_name)}` : ""}` : "课表待导入"}</p></div><button type="button" onClick={() => onObject("teaching:schedule")}>课程表</button></section><section className="edupi-teaching-home-section"><header><h2>本周课程</h2><button type="button" onClick={() => onObject("teaching:schedule")}>完整课程表</button></header><EduPiTimetableGrid slots={slots} onSelect={selectCourse} compact /></section><div className="edupi-teaching-home-columns"><section><header><h2>当前教学重点</h2><button type="button" onClick={() => onObject("teaching:knowledge")}>全部</button></header>{knowledge.slice(0, 4).map((item) => <details key={item.id}><summary><strong>{item.topic}</strong><span>{item.commonErrors[0]?.description || "暂无共性问题"}</span></summary><p>{item.strugglingStudents.length ? `需关注：${item.strugglingStudents.join("、")}` : "暂无需特别关注学生"}</p></details>)}</section><section><header><h2>备课任务</h2><button type="button" onClick={() => onObject("teaching:tasks")}>全部</button></header>{tasks.slice(0, 5).map((task) => <button type="button" key={taskKey(task)} onClick={() => onTask(task)}><strong>{taskDisplayTitle(task)}</strong><span>{task.dueDate || taskStatusLabel(task)}</span></button>)}</section></div></main>;
}
