"use client";

import type { EducationContract, TeacherTask } from "@/lib/edupi-education-contract";
import { matchesWorkspaceQuery as match } from "@/lib/edupi-domain-navigation";
import { isTaskActionable, taskDisplayTitle, taskKey, taskTypeLabel } from "@/lib/edupi-workbench";

export function EduPiReviewBoard({ data, query, onTask, onReviewTarget }: { data: EducationContract; query: string; onTask: (task: TeacherTask) => void; onReviewTarget: (target: { kind: "observation" | "memory_candidate"; id: string }) => void }) {
  const tasks = data.tasks.filter((task) => isTaskActionable(task) && match(`${task.title} ${task.sourceEventName || ""} ${task.student || ""}`, query));
  const observations = data.observations.filter((item) => (item.teacherReview.state === "pending_review" || item.teacherReview.state === "held") && match(`${item.text} ${item.observationId} ${item.evidenceIds.join(" ")}`, query));
  const memories = data.memoryCandidates.filter((item) => item.teacherReview.state !== "rejected" && (item.teacherReview.state === "pending_review" || item.teacherReview.state === "held") && match(`${item.proposedContent} ${item.candidateId} ${item.tags.join(" ")}`, query));
  return <main className="edupi-module-workspace edupi-review-board-workspace"><header className="edupi-module-heading"><div><span>教师判断中心</span><h1>待我确认</h1><p>{tasks.length + observations.length + memories.length} 项等待判断</p></div></header><div className="edupi-review-mini-board"><section><header><span>任</span><h2>任务审核</h2><em>{tasks.length}</em></header><div>{tasks.map((task) => <button type="button" key={taskKey(task)} onClick={() => onTask(task)}><strong>{taskDisplayTitle(task)}</strong><span>{taskTypeLabel(task)} · {task.dueDate || "日期待确认"}</span></button>)}{tasks.length === 0 ? <p>暂无任务</p> : null}</div></section><section><header><span>察</span><h2>观察确认</h2><em>{observations.length}</em></header><div>{observations.map((item) => <button type="button" key={item.observationId} onClick={() => onReviewTarget({ kind: "observation", id: item.observationId })}><strong>{item.text}</strong><span>{item.evidenceIds.length} 条依据</span></button>)}{observations.length === 0 ? <p>暂无观察</p> : null}</div></section><section><header><span>记</span><h2>记忆确认</h2><em>{memories.length}</em></header><div>{memories.map((item) => <button type="button" key={item.candidateId} onClick={() => onReviewTarget({ kind: "memory_candidate", id: item.candidateId })}><strong>{item.proposedContent}</strong><span>{item.tags.join(" · ") || "记忆候选"}</span></button>)}{memories.length === 0 ? <p>暂无记忆候选</p> : null}</div></section></div></main>;
}
