"use client";

import { useState } from "react";
import { openExternal } from "@/lib/desktop-native";

const DINGTALK_CONNECTOR_COMMAND = "npx -y @dingtalk-real-ai/dingtalk-connector@0.8.25 install";
const GUIDES: Record<string, { title: string; note: string }> = { email: { title: "邮箱", note: "向邮箱管理员申请 IMAP/SMTP 或 OAuth 应用信息。" }, sis: { title: "教务系统", note: "向学校教务管理员申请课表、校历和名单接口。" }, cloud_drive: { title: "云盘", note: "选择学校正在使用的云盘，再授权指定材料目录。" } };

async function copyText(value: string): Promise<void> { await navigator.clipboard.writeText(value); }

function SetupHeader({ title, status, onClose }: { title: string; status: string; onClose: () => void }) {
  const label = status === "configured" ? "已连接" : status === "credentials_verified" ? "已授权，待启用" : "约 3 分钟";
  return <header><div><span>连接设置</span><h2>{title}</h2><small>{label}</small></div><button type="button" onClick={onClose} aria-label="关闭连接设置">×</button></header>;
}

function FeishuSetup({ status, onClose, onConfigured }: { status: string; onClose: () => void; onConfigured: () => void }) {
  const [appId, setAppId] = useState(""); const [appSecret, setAppSecret] = useState("");
  const [registrationId, setRegistrationId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [copied, setCopied] = useState(false);
  const openLink = async (url: string) => { try { await openExternal(url); setMessage(null); } catch { setMessage("系统未能打开链接，请检查默认浏览器"); } };
  const copyMaximumPermissions = async () => { try { const response = await fetch("/api/edupi/connectors/feishu"); const result = await response.json() as { ok?: boolean; manifest?: { addons?: object; events?: string[]; callbacks?: string[] } }; if (!response.ok || !result.ok || !result.manifest?.addons) throw new Error(); const addons = { ...result.manifest.addons, events: { items: { tenant: result.manifest.events || [] } }, callbacks: { items: result.manifest.callbacks || [] } }; await copyText(JSON.stringify(addons, null, 2)); setCopied(true); setMessage(null); } catch { setMessage("最大权限清单暂不可用"); } };
  const startRegistration = async () => { setBusy(true); setMessage(null); try { const response = await fetch("/api/edupi/connectors/feishu/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "start" }) }); const result = await response.json() as { ok?: boolean; error?: string; registrationId?: string; verificationUrl?: string; requestedScopeCount?: number }; if (!response.ok || !result.ok || !result.registrationId || !result.verificationUrl) throw new Error(result.error || "一键授权启动失败"); setRegistrationId(result.registrationId); await openLink(result.verificationUrl); setMessage(`已申请 ${result.requestedScopeCount || 436} 项权限，确认后返回检查结果`); } catch (error) { setMessage(error instanceof Error ? error.message : "一键授权启动失败"); } finally { setBusy(false); } };
  const pollRegistration = async () => { if (!registrationId) return; setBusy(true); try { const response = await fetch("/api/edupi/connectors/feishu/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "poll", registrationId }) }); const result = await response.json() as { ok?: boolean; error?: string; status?: string }; if (response.status === 202) { setMessage("飞书还在等待确认"); return; } if (!response.ok || !result.ok || result.status !== "configured") throw new Error(result.error || "授权尚未完成"); setRegistrationId(null); setMessage("飞书应用已创建并连接"); onConfigured(); } catch (error) { setMessage(error instanceof Error ? error.message : "授权检查失败"); } finally { setBusy(false); } };
  const submitManual = async (event: React.FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); setMessage(null); try { const response = await fetch("/api/edupi/connectors/feishu", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ appId, appSecret }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error || "连接验证失败"); setAppSecret(""); setMessage("验证通过，飞书已连接"); onConfigured(); } catch (error) { setMessage(error instanceof Error ? error.message : "连接验证失败"); } finally { setBusy(false); } };
  return <section className="edupi-connector-setup" aria-label="飞书连接设置">
    <SetupHeader title="飞书机器人" status={status} onClose={onClose} />
    <div className="edupi-connector-setup__primary"><div><strong>最大权限一键接入</strong><span>创建应用、机器人、权限、事件与回调</span></div><button className="edupi-admin-primary" type="button" disabled={busy} onClick={() => void (registrationId ? pollRegistration() : startRegistration())}>{busy ? "处理中…" : registrationId ? "检查授权结果" : "一键创建并授权"}</button></div>
    <ol><li><strong>最大功能权限</strong><span>199 项应用权限 · 237 项用户权限</span><button type="button" onClick={() => void copyMaximumPermissions()}>{copied ? "已复制" : "复制最大权限"}</button></li><li><strong>开放平台</strong><span>最终权限以企业审批为准</span><button type="button" onClick={() => void openLink("https://open.feishu.cn/app")}>打开开放平台 ↗</button></li><li><strong>Mira 同类流程参考</strong><button type="button" onClick={() => void openLink("https://moonshot.feishu.cn/wiki/Aa4EwFLCGiwdntklc9vcPZdsn9c")}>打开参考文档 ↗</button></li></ol>
    {message ? <p className="edupi-connector-setup__message" role="status">{message}</p> : null}
    <details><summary>已有应用手动绑定</summary><form onSubmit={submitManual}><label>App ID<input value={appId} onChange={(event) => setAppId(event.target.value)} placeholder="cli_..." maxLength={68} autoComplete="off" /></label><label>App Secret<input type="password" value={appSecret} onChange={(event) => setAppSecret(event.target.value)} maxLength={128} autoComplete="off" /></label><button className="edupi-admin-primary" type="submit" disabled={busy || !appId.trim() || appSecret.length < 16}>验证并保存</button></form></details>
  </section>;
}

function DingTalkSetup({ status, onClose, onConfigured }: { status: string; onClose: () => void; onConfigured: () => void }) {
  const [clientId, setClientId] = useState(""); const [clientSecret, setClientSecret] = useState("");
  const [registrationId, setRegistrationId] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [copied, setCopied] = useState(false);
  const openLink = async (url: string) => { try { await openExternal(url); setMessage(null); } catch { setMessage("系统未能打开链接，请检查默认浏览器"); } };
  const startRegistration = async () => { setBusy(true); setMessage(null); try { const response = await fetch("/api/edupi/connectors/dingtalk/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "start" }) }); const result = await response.json() as { ok?: boolean; error?: string; registrationId?: string; verificationUrl?: string }; if (!response.ok || !result.ok || !result.registrationId || !result.verificationUrl) throw new Error(result.error || "一键授权启动失败"); setRegistrationId(result.registrationId); await openLink(result.verificationUrl); setMessage("在钉钉扫码创建机器人后，返回这里检查结果"); } catch (error) { setMessage(error instanceof Error ? error.message : "一键授权启动失败"); } finally { setBusy(false); } };
  const pollRegistration = async () => { if (!registrationId) return; setBusy(true); try { const response = await fetch("/api/edupi/connectors/dingtalk/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "poll", registrationId }) }); const result = await response.json() as { ok?: boolean; error?: string; status?: string }; if (response.status === 202) { setMessage("钉钉还在等待确认"); return; } if (!response.ok || !result.ok || result.status !== "credentials_verified") throw new Error(result.error || "授权尚未完成"); setRegistrationId(null); setMessage("钉钉授权完成，Stream 运行时待启用"); onConfigured(); } catch (error) { setMessage(error instanceof Error ? error.message : "授权检查失败"); } finally { setBusy(false); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); try { const response = await fetch("/api/edupi/connectors/dingtalk", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientId, clientSecret }) }); const result = await response.json() as { ok?: boolean; error?: string; status?: string }; if (!response.ok || !result.ok || result.status !== "credentials_verified") throw new Error(result.error || "连接验证失败"); setClientSecret(""); setMessage("凭据已验证，Stream 运行时待启用"); onConfigured(); } catch (error) { setMessage(error instanceof Error ? error.message : "连接验证失败"); } finally { setBusy(false); } };
  return <section className="edupi-connector-setup" aria-label="钉钉连接设置">
    <SetupHeader title="钉钉机器人" status={status} onClose={onClose} />
    <div className="edupi-connector-setup__primary"><div><strong>钉钉扫码一键接入</strong><span>创建机器人、授权并保存连接信息</span></div><button className="edupi-admin-primary" type="button" disabled={busy} onClick={() => void (registrationId ? pollRegistration() : startRegistration())}>{busy ? "处理中…" : registrationId ? "检查授权结果" : "扫码创建并授权"}</button></div>
    <ol><li><strong>钉钉官方模板</strong><span>权限由扫码账号与企业审批决定</span><button type="button" onClick={() => void openLink("https://open.dingtalk.com/")}>打开开放平台 ↗</button></li><li><strong>Stream 运行时</strong><span>{DINGTALK_CONNECTOR_COMMAND}</span><button type="button" onClick={() => void copyText(DINGTALK_CONNECTOR_COMMAND).then(() => setCopied(true)).catch(() => setMessage("复制失败"))}>{copied ? "已复制" : "复制运行时命令"}</button></li><li><strong>机器人开发教程</strong><button type="button" onClick={() => void openLink("https://open.dingtalk.com/tutorial/")}>打开官方教程 ↗</button></li></ol>
    {message ? <p className="edupi-connector-setup__message" role="status">{message}</p> : null}
    <details><summary>已有应用手动绑定</summary><form onSubmit={submit}><label>Client ID<input value={clientId} onChange={(event) => setClientId(event.target.value)} maxLength={128} autoComplete="off" /></label><label>Client Secret<input type="password" value={clientSecret} onChange={(event) => setClientSecret(event.target.value)} maxLength={128} autoComplete="off" /></label><button className="edupi-admin-primary" type="submit" disabled={busy || clientId.length < 8 || clientSecret.length < 16}>{busy ? "验证中…" : "验证并保存"}</button></form></details>
  </section>;
}

export function EduPiConnectorSetup(props: { connectorId: string; status: string; onClose: () => void; onConfigured: () => void }) {
  if (props.connectorId === "feishu") return <FeishuSetup {...props} />;
  if (props.connectorId === "dingtalk") return <DingTalkSetup {...props} />;
  const guide = GUIDES[props.connectorId] || { title: props.connectorId, note: "该连接器需要管理员提供接入信息。" };
  return <section className="edupi-connector-setup" aria-label={`${guide.title}连接设置`}><SetupHeader title={guide.title} status={props.status} onClose={props.onClose} /><p>{guide.note}</p></section>;
}
