import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { createRequire } from "node:module";
import { createJiti } from "jiti";
import ts from "typescript";
const require = createRequire(import.meta.url), jiti = createJiti(import.meta.url);
const dependencies = { "@/lib/request-security": await jiti.import("../../../../lib/request-security.ts"), "@/lib/bounded-form-data": await jiti.import("../../../../lib/bounded-form-data.ts") };
const calls = []; let stale = false;
dependencies["@/lib/edupi-preparation-artifact-server"] = { preparationArtifactRequest: async (action, input) => { calls.push({ action, input }); if (stale) throw Object.assign(new Error("conflict"), { code: "stale_revision" }); return { artifact: { content: input.content, revision: 2 }, unchanged: false }; } };
const route = { exports: {} };
new Function("require", "module", "exports", ts.transpileModule(fs.readFileSync(new URL("./route.ts", import.meta.url), "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText)(name => dependencies[name] || require(name), route, route.exports);
const post = body => route.exports.POST(new Request("http://localhost/api/edupi/preparation-artifact", { method: "POST", headers: { "Content-Type": "application/json", host: "localhost" }, body: JSON.stringify(body) }));
test("teacher API rejects actor/source/path injection and returns conflicts", async () => {
  const input = { artifactId: "a", expectedRevision: 1, content: "修订" };
  for (const extra of [{ actor: "agent" }, { source: {} }, { path: "/tmp/file" }]) assert.equal((await post({ ...input, ...extra })).status, 400);
  assert.equal(calls.length, 0);
  assert.equal((await post(input)).status, 200);
  assert.deepEqual(calls[0], { action: "revise", input: { artifact_id: "a", expected_revision: 1, content: "修订", actor: "teacher" } });
  stale = true; const response = await post(input); assert.equal(response.status, 409); assert.equal((await response.json()).code, "stale_revision");
});
